### ISSUE TITLE
Scrollbar Fix

### ISSUE THREAD

**Issue by cbraeuning** [ClemsonNIMS/NIMS-website#14]
Hovering over the infowindow and scrolling to very top or bottom causes double scrollbars on mac.
Windows seems to have 2 side by side always. Both issues in chrome.

**Comment by adgreene** [comment]
I'm no longer having this issue, but it also looks like Google Maps updated, so it's possible this was fixed on their side?

**Comment by cbraeuning** [comment]
Ya the update seems to have broken a lot, but I guess this isn't one of them.
