### ISSUE TITLE
Home button on navbar doesn't work

### ISSUE THREAD

**Issue by cbraeuning** [ClemsonNIMS/NIMS-website#7]

**Comment by MacePapa12** [comment]
Fixed. Can be checked off of the issues list.

**Comment by MacePapa12** [comment]
As a note, the home option is somewhat redundant if the NIMS option is clickable. It makes sense that the NIMS link would take you back to the home page, so home is not needed.

**Comment by cbraeuning** [comment]
It is intentionally redundant, never know which the user expects to work. It doesn't hurt to have both functional.
